runtime: python
service: tools
env: flex
entrypoint: gunicorn app:app --limit-request-line 0 --timeout 600

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
